// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucggnndtelrueihryqve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZ2dubmR0ZWxydWVpaHJ5cXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjY0NTAsImV4cCI6MjA1MjgwMjQ1MH0.HwObHKOweJca8xDiL33aLNtwTeN4rs7Vj5auPWb5_sI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);